// export * from './RequestMethod.enum'
export * from './HttpStatus.enum'
// export * from './ApplySource.enum'
// export * from './ApplyStatus.enum'
// export * from './ApplyType.enum'
// export * from './Borrower.enum'
// export * from './BorrowerType.enum'
// export * from './BusinessType.enum'
// export * from './CheckType.enum'
// export * from './CustomerType.enum'
// export * from './EmployeeType.enum'
// export * from './ApplyPurpose.enum'
// export * from './LoanType.enum'
// export * from './RefundPeriod.enum'
// export * from './RelationType.enum'
// export * from './State.enum'
// export * from './RouteParamtypes.enum'
// export * from './OfficialLevel.enum'
// export * from './ImageType'
// export * from './SaleChannel'
// export * from './ActionType.enum'
// export * from './fragment.enum'
export * from './HttpCode.enum'
// export * from './Manage.enum'
// export * from './ActionDetail.enum'
// export * from './Result.enum'
// export * from './ApplyProperties.enum'
// export * from './RiskRuleType.enum'
// export * from './RejectionReason.enum'
// export * from './Rejection.enum'
// export * from './FlowType.enum'
// export * from './CoreNameType.enum'
// export * from './CoreContact.enum'
// export * from './ContactType.enum'
// export * from './TemplateId.enum'
// export * from './QueryChannel.enum'
// export * from './MonitorScope.enum'
// export * from './SendTarget.enum'
// export * from './PurposeCN.enum'
// export * from './Permission.enum'
// export * from './PutOutType.enum'
// export * from './Bank.enum'
// export * from './Serialno.enum'
// export * from './CreditStatus.enum'
// export * from './Source4Inner.enum'
// export * from './AttachmentType.enum'
// export * from './RejectTimeScope.enum'
// export * from './OrgId.enum'
// export * from './CommentName.enum'
// export * from './TeleType.enum'
// export * from './CmaStatus.enum'

// export function transInt2String4Core(field) {
//   return typeof field === 'number' ? ('0' + String(field)) : field
// }
